name: Build for GENERIC ESP32 C3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone MicroPython
        run: |
          git clone https://github.com/micropython/micropython.git
          cd micropython
          git checkout v1.25.0
          git submodule update --init --recursive
    
      - name: Build mpy-cross
        run: |
          cd micropython/mpy-cross
          make

      - name: Build MicroPython Firmware
        run: |
          cd micropython/ports/esp32
          make USER_C_MODULES=../../../st7789/micropython.cmake

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: micropython/ports/esp32/build-ESP32_GENERIC_C3/firmware.bin